export const fields = {
  username: {
    label: 'Name',
    name: 'username',
    type: 'text',
    placeholder: 'Name',
    title: '*The Name field must be more than 2 and less than 15 characters',
    required: true,
  },
  surname: {
    label: 'Surname',
    name: 'surname',
    type: 'text',
    placeholder: 'Surname',
    title: '*The Surname field must be more than 2 and less than 50 characters',
    required: false,
  },
  email: {
    label: 'Email',
    name: 'email',
    type: 'text',
    placeholder: 'Email',
    title: '*Enter a valid email',
    required: true,
  },
  password: {
    label: 'Password',
    name: 'password',
    type: 'password',
    placeholder: 'Password',
    title:
      '*The Password field must be more than 2 and less than 21 characters',
    required: true,
  },
  city: {
    label: 'City',
    name: 'city',
    type: 'text',
    placeholder: 'City',
    title: '*The City field must be more than 2 and less than 50 characters',
    required: false,
  },
  address: {
    label: 'Address',
    name: 'address',
    type: 'text',
    placeholder: 'Address',
    title: '*The Address field must be more than 2 and less than 50 characters',
    required: false,
  },
  phone: {
    label: 'Phone number',
    name: 'phone',
    type: 'tel',
    placeholder: 'Phone number',
    title: '*Enter a valid phone number',
    required: false,
  },
  search: {
    name: 'search',
    type: 'text',
    title: '',
    required: false,
  },
  keyword: {
    name: 'keyword',
    type: 'text',
    title: '',
    required: false,
  },
  title: {
    label: 'Title',
    name: 'title',
    type: 'text',
    placeholder: 'Title',
    title: '*The Title field must be more than 2 and less than 200 characters',
    required: true,
  },
  street: {
    label: 'Street',
    name: 'street',
    type: 'text',
    placeholder: 'Street',
    title: '*The Street field must be more than 2 and less than 50 characters',
    required: true,
  },
  building: {
    label: 'Building',
    name: 'building',
    type: 'text',
    placeholder: 'Building',
    title: '*The Building field must be more than 1 and less than 4 characters',
    required: false,
  },
  apartment: {
    label: 'Apartment',
    name: 'apartment',
    type: 'text',
    placeholder: 'Apartment',
    title:
      '*The Apartment field must be more than 1 and less than 4 characters',
    required: false,
  },
  livingRooms: {
    label: 'LivingRooms',
    name: 'livingRooms',
    type: 'text',
    placeholder: 'Number of living rooms',
    title: '*Number of living rooms field must have no more than 2 characters',
    required: true,
  },
  qtyAdults: {
    label: 'QtyAdults',
    name: 'qtyAdults',
    type: 'text',
    placeholder: 'Number of adults',
    title: '*Number of adults field must have no more than 2 characters',
    required: true,
  },
  qtyChildrens: {
    label: 'QtyChildrens',
    name: 'qtyChildrens',
    type: 'text',
    placeholder: 'Number of childrens',
    title: '*Number of childrens field must have no more than 2 characters',
    required: true,
  },
  value: {
    label: 'Value',
    name: 'value',
    type: 'text',
    placeholder: 'Price per night',
    title: '*The Price per night field must have no more than 4 characters',
    required: true,
  },
  accessCode: {
    label: 'Access Code',
    name: 'accessCode',
    type: 'text',
    placeholder: 'Access Code',
    title: '*Access Code must be 9 letters or digits',
    required: true,
  },
};
